name: BetterAnticheat
version: 1.0.0
main: better.anticheat.spigot.BetterAnticheatSpigot
api-version: 1.13
load: POSTWORLD
softdepend:
  - BetterReload
depend:
  - packetevents
authors:
  - am noah

# Spigot specific libraries ONLY that are ONLY caused by spigot not having libraries everyone else has.
libraries:
  - org.slf4j:slf4j-api:2.0.17
  - org.apache.logging.log4j:log4j-slf4j18-impl:2.18.0