name: BetterAnticheat
version: 0.0.1
main: better.anticheat.paper.BetterAnticheatPaper
api-version: 1.13
load: POSTWORLD
folia-supported: true
softdepend:
  - BetterReload
depend:
  - packetevents
authors:
  - am noah