name: BetterAnticheat
version: 1.0.0
main: better.anticheat.paper.BetterAnticheatPaper
api-version: 1.13
load: POSTWORLD
folia-supported: true
softdepend:
  - BetterReload
depend:
  - packetevents
authors:
  - am noah
libraries:
  - it.unimi.dsi:fastutil:8.5.16
  - org.yaml:snakeyaml:2.4
  - io.github.revxrsal:lamp.bukkit:4.0.0-rc.12
  - io.github.revxrsal:lamp.brigadier:4.0.0-rc.12
  - io.github.revxrsal:lamp.common:4.0.0-rc.12
  - com.github.haifengl:smile-core:4.4.0
  - com.github.haifengl:smile-plot:4.4.0
  - com.alibaba.fastjson2:fastjson2:2.0.57
  - com.github.luben:zstd-jni:1.5.6-7