name: BetterAnticheat
version: 1.0.0
main: better.anticheat.paper.BetterAnticheatPaper
api-version: 1.13
load: POSTWORLD
folia-supported: true
softdepend:
  - BetterReload
depend:
  - packetevents
authors:
  - am noah
libraries:
  - it.unimi.dsi:fastutil:8.5.16
  - org.yaml:snakeyaml:2.4